### ISSUE TITLE
placement of share/applications when installing as root

### ISSUE THREAD

**Issue by emillynge** [welshjf/install_freedesktop#1]
Hi, Thanks for making this little marvel :)

I have tried using it for a system wide installation and found that it puts the *.desktop files in `/usr/local/share/applications` which is not indexed by default by the KDE launcher.

The correct path would be `/usr/share/applications`. I think it would require an if-else statement to implement this as you cannot depend on the data-dir providing a useful root for .../share/applications

regards Emil

/Edit
I'm apparantly just a bit too impatient. Just needed a reboot for the desktop entry to become searchable. It is however still usual for .desktop files to reside in either `/usr/share/applications` or `~/.local/share/applications`

**Comment by welshjf** [comment]
Glad to hear it. I think kbuildsycoca* should work too instead of rebooting.

/usr/local/share/applications seems like the correct place to me if the binary is in /usr/local/bin. The data-dir can be set on the command line if necessary.

I thought ~/.local/share/applications was working for a --user install, as mentioned in the docs. Strangely, the module is not working at all when I test now. I wonder if the setuptools.command.install.sub_commands plumbing has changed recently.
